# Copyright (c) 2015 Crytek.
# WAF-based build system

def build(bld):	

	bld.CryEngineStaticModule( 
		target    = 'lua', 
		vs_filter = 'Libs',
		file_list = 'lua.waf_files',

		module_provides = dict(
			includes = [ Path('Code/SDKs/Lua/src'), ],
		),
	)
